
default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: blog_api_test

#
production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: <%= ENV["BLOG_API_DATABASE_PASSWORD"] %>
